name: nyxx_pagination
description: Paginates lists into multi-page multi selects for use with nyxx.
version: 1.0.0

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  nyxx: ^3.2.7
  nyxx_interactions: ^3.3.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
